-- MySQL Script generated by MySQL Workbench
-- Wed Apr 21 22:23:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dip-assignmen-star
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dip-assignmen-star` ;

-- -----------------------------------------------------
-- Schema dip-assignmen-star
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dip-assignmen-star` DEFAULT CHARACTER SET utf8 ;
USE `dip-assignmen-star` ;

-- -----------------------------------------------------
-- Table `dip-assignmen-star`.`klant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dip-assignmen-star`.`klant` ;

CREATE TABLE IF NOT EXISTS `dip-assignmen-star`.`klant` (
  `idklant` INT NOT NULL,
  PRIMARY KEY (`idklant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dip-assignmen-star`.`filiaal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dip-assignmen-star`.`filiaal` ;

CREATE TABLE IF NOT EXISTS `dip-assignmen-star`.`filiaal` (
  `idfiliaal` INT NOT NULL,
  PRIMARY KEY (`idfiliaal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dip-assignmen-star`.`aankoop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dip-assignmen-star`.`aankoop` ;

CREATE TABLE IF NOT EXISTS `dip-assignmen-star`.`aankoop` (
  `idaankoop` INT NOT NULL,
  `filiaal_idfiliaal` INT NOT NULL,
  `klant_idklant` INT NOT NULL,
  `datum` DATETIME NOT NULL,
  `aantal` VARCHAR(45) NULL,
  INDEX `fk_aankoop_klant1_idx` (`klant_idklant` ASC) ,
  INDEX `fk_aankoop_filiaal1_idx` (`filiaal_idfiliaal` ASC) ,
  PRIMARY KEY (`idaankoop`, `klant_idklant`),
  CONSTRAINT `fk_aankoop_klant1`
    FOREIGN KEY (`klant_idklant`)
    REFERENCES `dip-assignmen-star`.`klant` (`idklant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aankoop_filiaal1`
    FOREIGN KEY (`filiaal_idfiliaal`)
    REFERENCES `dip-assignmen-star`.`filiaal` (`idfiliaal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dip-assignmen-star`.`eenheid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dip-assignmen-star`.`eenheid` ;

CREATE TABLE IF NOT EXISTS `dip-assignmen-star`.`eenheid` (
  `ideenheid` INT NOT NULL,
  `omschrijving` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ideenheid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dip-assignmen-star`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dip-assignmen-star`.`product` ;

CREATE TABLE IF NOT EXISTS `dip-assignmen-star`.`product` (
  `idproduct` INT NOT NULL,
  `omschrijving` VARCHAR(45) NOT NULL,
  `inhoudsaantal` VARCHAR(45) NOT NULL,
  `eenheid_ideenheid` INT NOT NULL,
  PRIMARY KEY (`idproduct`),
  INDEX `fk_product_eenheid_idx` (`eenheid_ideenheid` ASC) ,
  CONSTRAINT `fk_product_eenheid`
    FOREIGN KEY (`eenheid_ideenheid`)
    REFERENCES `dip-assignmen-star`.`eenheid` (`ideenheid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dip-assignmen-star`.`filiaal_has_klant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dip-assignmen-star`.`filiaal_has_klant` ;

CREATE TABLE IF NOT EXISTS `dip-assignmen-star`.`filiaal_has_klant` (
  `filiaal_idfiliaal` INT NOT NULL,
  `klant_idklant` INT NOT NULL,
  PRIMARY KEY (`filiaal_idfiliaal`, `klant_idklant`),
  INDEX `fk_filiaal_has_klant_klant1_idx` (`klant_idklant` ASC) ,
  INDEX `fk_filiaal_has_klant_filiaal1_idx` (`filiaal_idfiliaal` ASC) ,
  CONSTRAINT `fk_filiaal_has_klant_filiaal1`
    FOREIGN KEY (`filiaal_idfiliaal`)
    REFERENCES `dip-assignmen-star`.`filiaal` (`idfiliaal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filiaal_has_klant_klant1`
    FOREIGN KEY (`klant_idklant`)
    REFERENCES `dip-assignmen-star`.`klant` (`idklant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dip-assignmen-star`.`aankoop_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dip-assignmen-star`.`aankoop_has_product` ;

CREATE TABLE IF NOT EXISTS `dip-assignmen-star`.`aankoop_has_product` (
  `aankoop_idaankoop` INT NOT NULL,
  `aankoop_klant_idklant` INT NOT NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`aankoop_idaankoop`, `aankoop_klant_idklant`, `product_idproduct`),
  INDEX `fk_aankoop_has_product_product1_idx` (`product_idproduct` ASC) ,
  INDEX `fk_aankoop_has_product_aankoop1_idx` (`aankoop_idaankoop` ASC, `aankoop_klant_idklant` ASC) ,
  CONSTRAINT `fk_aankoop_has_product_aankoop1`
    FOREIGN KEY (`aankoop_idaankoop` , `aankoop_klant_idklant`)
    REFERENCES `dip-assignmen-star`.`aankoop` (`idaankoop` , `klant_idklant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aankoop_has_product_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `dip-assignmen-star`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
